### ISSUE TITLE
中级：错误－只有群组的“创始者”可以“修改”“删除”群组资讯－@group

### ISSUE THREAD

**Issue by DJ-MinorG** [growthschool/homework-3#12]
位置：Home 第二期 Rails 全栈班（课前中级练习教材） Syllabus 只有群组的“创始者”可以“修改”“删除”群组资讯
https://xin.ontrackapp.com/posts/243

 原教程：step10
`加入 <% if current_user && current_user == group.user %> 的判断式`

错误描述：这里应该是@group非group，下面的程式码是对的，这里描述有问题，我自己就贴的描述：P

建议：`加入 <% if current_user && current_user == @group.user %> 的判断式`

**Comment by setaja** [comment]
ok 已修
