### ISSUE TITLE
中级：建议 import 的解说再详细一些

### ISSUE THREAD

**Issue by DJ-MinorG** [growthschool/homework-3#13]
位置：帮 Rails 专案穿上衣服“Bootstrap”
https://xin.ontrackapp.com/posts/225

原教程：解说
`import 是什么？
是 scss 内引入“模组”的意思。`

问题：这个解释还是很难理解import的意思，因为解释中又出现了新的词汇“模组”，变成了用未知解释未知

建议：可不可以再详细解释一下，或链接去一个更好的解释

**Comment by setaja** [comment]
改成這樣：「\* 是 scss 内引入“模组”的意思。透过这样的方式去引用其他资源，就不需要自己从头开始制作。比方说你要穿衣服，直接买一件来穿就省事很多，不需要自己跑去买布、搞裁缝那些。」

初學者應該比較能夠理解吧？

**Comment by DJ-MinorG** [comment]
好多啦 ：）
