### ISSUE TITLE
中级：Rails 版本已经有5.0.0.1

### ISSUE THREAD

**Issue by DJ-MinorG** [growthschool/homework-3#3]
**位置：**Home 第二期 Rails 全栈班（课前中级练习教材） Syllabus 建立新专案
**原教程：**Step 2. 安装 Rails （版本 5.0.0)
。。。
确认现在这个版本是 5.0.0 。

**建议：**我的版本已经是5.0.0.1，教程可以改为5.0.0或以上？小问题可以不改

**Comment by setaja** [comment]
ok  已修訂
