### ISSUE TITLE
中级：拼写错误“bootstrap-saas”

### ISSUE THREAD

**Issue by DJ-MinorG** [growthschool/homework-3#4]
位置：https://xin.ontrackapp.com/posts/225
Home 第二期 Rails 全栈班（课前中级练习教材） Syllabus 帮 Rails 专案穿上衣服“Bootstrap”
原教程：step1。。。
在 Rails 上要帮专案穿上 Bootstrap，用的是 bootstrap-saas 这个套件

错误：bootstrap-saas

建议：bootstrap-sass

**Comment by setaja** [comment]
ok 已修訂
