### ISSUE TITLE
中级：建议增加rails c退出

### ISSUE THREAD

**Issue by DJ-MinorG** [growthschool/homework-3#5]
位置：https://xin.ontrackapp.com/posts/228
Home 第二期 Rails 全栈班（课前中级练习教材） Syllabus 建立讨论群的架构

问题描述：因为step6进了console，如果是纯菜鸟可能不知道怎么退出console，甚至step7直接在console里面继续做

建议：Step 7. git 存档后面加一句 
`exit` 退出rails console
git add .
。。。

**Comment by setaja** [comment]
ok 這個好，已修訂
