### ISSUE TITLE
中级：建议－flash的正确写法

### ISSUE THREAD

**Issue by DJ-MinorG** [growthschool/homework-3#7]
位置：Home 第二期 Rails 全栈班（课前中级练习教材） Syllabus 实作讨论群“删除”功能
原教程：step 1
...
-  def destroy
-    @group = Group.find(params[:id])
-    @group.destroy
-    redirect_to groups_path, alert: "Group deleted"
-  end

问题：记得老师后来禁止我们写 redirect_to groups_path, alert: "Group deleted"，这样的形式，我们的习惯养成可能有一部分来源于中级，不如这里直接改成对的写法？？？

建议：  
def destroy
     @group = Group.find(params[:id])
     @group.destroy
      flash[:alert] = "Group deleted"
     redirect_to groups_path
  end

**Comment by setaja** [comment]
好，這部分我先修改，如果還有其他建議在跟我說。
